name: Build and Deploy
on:
  push:
    paths: ["src/lib/components/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          npm i -f
          npm run sb-build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.3
        with:
          branch: main
          folder: design-system
          clean: true
          target-folder: docs # The folder that we serve our Storybook files from
